// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0UEgZyBkSTtSLkspIgRjE4X-UD3wPwc',
    appId: '1:951099922215:web:e507c9d06d6b627c873b02',
    messagingSenderId: '951099922215',
    projectId: 'classw6-6ffd2',
    authDomain: 'classw6-6ffd2.firebaseapp.com',
    storageBucket: 'classw6-6ffd2.firebasestorage.app',
    measurementId: 'G-LZDZ0ZCC2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6AKR4JLlYZGA1lsKYOc5XiMYBKDWpMs',
    appId: '1:951099922215:android:94d4b458534fa81e873b02',
    messagingSenderId: '951099922215',
    projectId: 'classw6-6ffd2',
    storageBucket: 'classw6-6ffd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdoM1v1EOB6Q_ElKMtInzrp6TRDURxvAk',
    appId: '1:951099922215:ios:d68d72643edb3bc7873b02',
    messagingSenderId: '951099922215',
    projectId: 'classw6-6ffd2',
    storageBucket: 'classw6-6ffd2.firebasestorage.app',
    iosBundleId: 'com.example.classw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdoM1v1EOB6Q_ElKMtInzrp6TRDURxvAk',
    appId: '1:951099922215:ios:d68d72643edb3bc7873b02',
    messagingSenderId: '951099922215',
    projectId: 'classw6-6ffd2',
    storageBucket: 'classw6-6ffd2.firebasestorage.app',
    iosBundleId: 'com.example.classw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs0UEgZyBkSTtSLkspIgRjE4X-UD3wPwc',
    appId: '1:951099922215:web:f453a5b844ef27d8873b02',
    messagingSenderId: '951099922215',
    projectId: 'classw6-6ffd2',
    authDomain: 'classw6-6ffd2.firebaseapp.com',
    storageBucket: 'classw6-6ffd2.firebasestorage.app',
    measurementId: 'G-M1WEKEXZSJ',
  );
}
